apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: your-docker-registry/auth-service:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_DRIVER
          value: "mysql"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: dbname
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
