name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env file with Secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env

      - name: Deploy to server (placeholder)
        run: |
          # This is a placeholder for your deployment script.
          # You would typically use a tool like rsync, scp, or a dedicated deployment action.
          # For example:
          # rsync -avz -e "ssh -o StrictHostKeyChecking=no" . user@host:/path/to/your/app
          echo "Deploying to server..."
          ls -la # List files to show .env is created and included
          echo "Deployment complete."